### ISSUE TITLE
Liquid Tutorial

### ISSUE THREAD

**Issue by DimosPagakis** [ioniodi/site1#137]
Πιο κάτω βρίσκεται ένα link με μια αρκετά καλή πρώτη εξήγηση του πώς δουλεύει το liquid και τα στατικά site.Μπορούμε να κάνουμε και ομαδική στο facebook για πιο γρήγορο share αντίστοιχων video 

https://www.youtube.com/watch?v=TRTmAlNA92c

**Comment by DimosPagakis** [comment]
https://www.youtube.com/watch?v=iWowJBRMtpc

**Comment by DimosPagakis** [comment]
https://www.youtube.com/watch?v=_f4aly6xblQ&list=PLrxYIq_0LFJc0TfNbv24cuFD1IaUtkzrh&index=1

**Comment by epidrome** [comment]
υπάρχει αρκετό υλικό, για να μην χαθείτε μερικές ιδέες:

1. το liquid φτιάχτηκε από το shopify οπότε εκεί είναι η σίγουρη τεκμηρίωση
2. το jekyll ίσως να μην χρησιμοποιεί όλες τις δυνατότητες του liquid οπότε καλύτερα να κοιτάτε και την αντίστοιχη τεκμηρίωση και φόρουμ
3. μερικά χρήσιμα λινκ: https://talk.jekyllrb.com/  https://jekyllrb.com/help/  http://stackoverflow.com/questions/tagged/jekyll?sort=votes&pageSize=15

*καλό το βίντεο και το διάβασμα, αλλά ο καλύτερος τρόπος είναι να κάνεις σταδιακά πολύ μικρές αλλαγές σε παραδείγματα που δουλεύουν.*
