### ISSUE TITLE
Mis en

### ISSUE THREAD

**Issue by DimosPagakis** [ioniodi/site1#43]
Δεχτήκατε το "Εισαγωγή στα πληροφοριακά συστήματα" στα αγγλικά αλλά παρατήρησα ότι δεν το είχα γράψει στο φάκελο courses-en αλλά στο courses.Κάντε το revert αν μπορείτε!

**Comment by epidrome** [comment]
Αφού βρήκες το λάθος καλύτερα να το διορθώσεις με ένα νέο αίτημα.
