### ISSUE TITLE
Σελίδες επιλογής

### ISSUE THREAD

**Issue by DimosPagakis** [ioniodi/site1#61]
Έχω επιλέξει σαν σελίδες επιλογής 2 υποσελίδες στο tab του προπτυχιακού.Σε ποιον φάκελο θα δημιουργηθούν τα markdown?

**Comment by epidrome** [comment]
για την ώρα θα τα βάλουμε κάπως χύμα μέσα στά:
_docs
_docs-en

στο μέλλον θα συζητήσουμε αν υπάρχει καλύτερη οργάνωση.

ευχαριστώ!
