### ISSUE TITLE
Conflict at authors.yml

### ISSUE THREAD

**Issue by DimosPagakis** [ioniodi/site1#68]
Κύριε εξέτασα λίγο την κατάσταση και κατέληξα στο εξής.

Το αρχείο που δεχτήκατε αρχικά έχει τον Κουρουθανάση σαν kourou-en ενώ στα μαθήματα είναι δηλωμένος σαν pkour και pkour-en αντίστοιχα εφόσον είπατε πως είναι καλύτερη τακτική.

Νομίζω καλύτερα να διαγράψατε το kourou-en από το authors.yml στο master σας τώρα που είναι αρχή ακόμα.Γίνεται;Συμφωνείτε;

**Comment by epidrome** [comment]
συγκρούσεις που προκύπτουν από τέτοια λάθη μπορεί να τις διορθώνει ο ίδιος ο δημιουργός του αιτήματος όπως παρατηρώ ότι έγινε
