### ISSUE TITLE
Μd σελίδων επιλογής

### ISSUE THREAD

**Issue by DimosPagakis** [ioniodi/site1#91]
Για τις σελίδες επιλογής τι μορφή θα πρέπει να έχει το md?

Eυχαριστώ!

**Comment by epidrome** [comment]
προτάσεις δεκτές,

σίγουρα θα πρέπει να έχει τα βασικά που έχουν όλες οι σελίδες και τα οποία χρησιμοποιούνται για να βγαίνουν οι λίστες των σελίδων:

ref: 
title: 
excerpt:

ανάλογα με το είδος και το περιέχομενο της σελίδας μερικά ακόμη χρήσιμα πεδία:

author:
web:
